AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-static-hosting

  Sample SAM Template for serverless-static-hosting

Globals:
  Function:
    Timeout: 3
  Api:
    BinaryMediaTypes:
      - '*~1*'
      - image~1gif
      - image~1jpg
      - image~1png
      - font~1ttf
      - application~1font-woff
      - application~1font-woff2

Resources:
  StaticHostingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: static_server/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        RootEndpoint:
          Type: Api
          Properties:
            Method: any
            Path: /
        # We need two endpoints, one for the root and one for everything else
        # https://github.com/awslabs/aws-sam-cli/issues/437
        # https://www.valtech.com/insights/serving-images-through-aws-api-gateway-from-serverless-lambda_proxy-function/
        EverythingElse:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StaticHostingApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  StaticHostingFunction:
    Description: "StaticHostingFunction ARN"
    Value: !GetAtt StaticHostingFunction.Arn
  StaticHostingFunctionIamRole:
    Description: "Implicit IAM Role created for StaticHostingFunction"
    Value: !GetAtt StaticHostingFunctionRole.Arn
